import type { BuyerUser, NotificationItem, Property, Society } from "./types";

export const properties: Property[] = [
  {
    id: "p1",
    title: "10 Marla House, DHA Phase 6",
    price: "Rs 2.4 Crore",
    pricePerUnit: "Rs 24 Lakh",
    location: "DHA Phase 6, Lahore",
    area: "10 Marla",
    beds: 5,
    baths: 6,
    type: "House",
    verified: true,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAb0lwPZJkt18LWpBo-E_hO-lEPKVIb0qoEYuddf1BuOJFy5aYVUgX7oJ3hTm34ZZjMjEKfsVSrREOrQprjxVQZW7MCXHiptgwgbonjHQg7wkQxZkqJ6_gO7G2qLRzg-RbTJILN4CzdWV5rtso-xawWNXFXFNV3UAyVRDcJkGWp1V8f0SnCNsJuTNwqXy-hRCrdw1jLABiTlVGRw2XEIxjw0aAUUs90GdjX6AzycF8Bwua96ZfGA5Ge",
    investmentScore: 78,
    predictedPrice: "Rs 2.6 Crore",
    predictedChangePct: 8.3,
    ownership: "Freehold",
    possession: "Ready",
    yearBuilt: 2020,
    description: [
      "Nestled in the prime location of DHA Phase 6, this exquisite 10 Marla modern residence offers an unparalleled blend of luxury and functionality. Designed by renowned architects, the property boasts high-end finishes, Italian tiles, and imported sanitary fittings throughout.",
      "The spacious layout includes five master bedrooms with ensuite bathrooms, a designer kitchen, and multiple lounging areas. The house is strategically positioned to ensure maximum natural ventilation and sunlight, providing an airy, tranquil atmosphere for a modern family lifestyle.",
    ],
  },
  {
    id: "p2",
    title: "1 Kanal Villa, Bahria Town Phase 8",
    price: "Rs 4.8 Crore",
    pricePerUnit: "Rs 24 Lakh",
    location: "Bahria Town Phase 8, Rawalpindi",
    area: "1 Kanal",
    beds: 6,
    baths: 7,
    type: "House",
    verified: true,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAPctgQyskgZW5cjiJ1EuXQ8OXlb_eqU1tItFmXn1nr1vwLFdeDM0A3Rzdu71tAG0FhE1bZtCT8irhvf5UVZu05wA7ns3KXLH5zv3Gy95bRuBz9Q_g8j0a5K2lnNZtD86ucgoNM_zB5CztbAla5Wnp1B-P72VzL4gDW5jfrX3vW7LJPe0VXA_qPdGqR49D1MAZuKuviM4PP2kW7rgmHpgXZ2Udpj7rkAlA4sZnj7bJOfRpiIdRd3er_",
    investmentScore: 71,
    predictedPrice: "Rs 5.1 Crore",
    predictedChangePct: 6.3,
    ownership: "Freehold",
    possession: "Ready",
    yearBuilt: 2021,
  },
  {
    id: "p3",
    title: "7 Marla House, Gulberg Residencia",
    price: "Rs 1.9 Crore",
    pricePerUnit: "Rs 27 Lakh",
    location: "Gulberg Residencia, Islamabad",
    area: "7 Marla",
    beds: 4,
    baths: 5,
    type: "House",
    verified: true,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDoWIBvMBy8U6IoBja0nZbnQM5vbU-ACe9abgMrKkuQ89dQA1PJzOPUOdgCk17oXY14AVFAJbiBjAstfyOuEhP7VwkohR2HM9Ab0rl0O48XJW2MURAUf8hc9azbplbA2ieBST_dpoeFSRJx3kC-iDMbgHX8IgMxE94GBnJacTRVnxYbgkJh6uIKyj0J4jY8E4IPdSx6-nf5pCNwhvgBmUtBRP1Wg5rKBIosjx67pIVvT9xkAlg93xGL",
    investmentScore: 65,
    predictedPrice: "Rs 2.0 Crore",
    predictedChangePct: 4.1,
    ownership: "Leasehold",
    possession: "Ready",
    yearBuilt: 2019,
  },
  {
    id: "p4",
    title: "Apartment, Clifton Block 5",
    price: "Rs 3.5 Crore",
    pricePerUnit: "Rs 18 Lakh",
    location: "Clifton Block 5, Karachi",
    area: "3 Beds",
    beds: 3,
    baths: 4,
    type: "Apartment",
    verified: true,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuA9WFIo8jzz7zROHxUD2Rp9kAZhEDigLOZFG37KO5PVPU-TsZ1E9-vy_Uuyj7JDJZtTTj3LR4wCUocnXylZ135tMMS6yF-3e0DNRhHNgSkvQq3u6N7EC3U8usH-vVh0mAsYl3bkc9l2XZNcDP2gG68XZ4HutcjUftIaC_4GmUjkPEYMF59t4V1SNSoG7Lo4xm-mtonUMm4pFQtWkpv12fDh5tTX_8JGN1Dcw7GaIHumG8QJQhfiA7Wi",
    investmentScore: 69,
    predictedPrice: "Rs 3.7 Crore",
    predictedChangePct: 5.7,
    ownership: "Freehold",
    possession: "Ready",
    yearBuilt: 2022,
  },
  {
    id: "p5",
    title: "1 Kanal House, State Life Phase 1",
    price: "Rs 5.2 Crore",
    pricePerUnit: "Rs 26 Lakh",
    location: "State Life Phase 1, Lahore",
    area: "1 Kanal",
    beds: 5,
    baths: 5,
    type: "House",
    verified: true,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAc1oERGNQoU4zBFMPWVctrXoewQGqRUGqpoAqeqivlmEj6HOY-4ahnpTmMI0NY6mlJxh40lRqO2P2RT95XRKNVEG4_ptINY_fP4qv5Q0oI01NXQtcZhletmcaq0-e3WokwxWpRkOJPBktS1Y1vw78knG3MMRaVRBszQ6sVwpAiO68XkkVGdHlfRjtltxpISDeVgozkooQhmTybENx5bYmYNdj0QfW0gkazQcsS_Tcs1aczfZsS1two",
    investmentScore: 74,
    predictedPrice: "Rs 5.6 Crore",
    predictedChangePct: 7.7,
    ownership: "Freehold",
    possession: "Ready",
    yearBuilt: 2020,
  },
  {
    id: "p6",
    title: "Studio, Emaar Canyon Views",
    price: "Rs 1.1 Crore",
    pricePerUnit: "Rs 55 Lakh",
    location: "Emaar Canyon Views, Islamabad",
    area: "Studio",
    beds: 2,
    baths: 2,
    type: "Apartment",
    verified: true,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuD_aabJyuTY2R1B_VFW2tY_iS8Ysw7leFMVCCz1kyq7XGJsr_GbihnmKQw9AjEy3oqcUSvZPtAHNfBCc0BW2y1wXMSvxNIWtfzbeoGOL6Lv6wldP4iVj7_aR9LYU9hcyX5kZBgO4uygyiiCb682hE9P3iCfjLy-r1CEiFvS7fAQWl_IQoo7WIbV49QM6aPKX9uSb_dq2P3OW524tr1XLcYdNBO2jKXZbhIBQ2Ml-NN4hE55OHQx4ROJ",
    investmentScore: 58,
    predictedPrice: "Rs 1.2 Crore",
    predictedChangePct: 3.2,
    ownership: "Freehold",
    possession: "Ready",
    yearBuilt: 2023,
  },
  {
    id: "p7",
    title: "2 Kanal House, DHA Phase 8",
    price: "Rs 7.5 Crore",
    pricePerUnit: "Rs 18 Lakh",
    location: "DHA Phase 8, Karachi",
    area: "2 Kanal",
    beds: 6,
    baths: 6,
    type: "House",
    verified: true,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBBPs1UO2qyIXJGWeeil6DWQwua7G_rNrpDjNycIA96nOWJttWB9FQIAtx6eiHm0Vq9MKeZnq947EP71M0ICSpK9Qj_rvW7ZLmCggl9dl0KIPJILTrGOkES6QPxvmt7zlRcC0Gubz-ePIhyVybKDi9LHXBoOo9z2M2vUKlvmveipW4ivz2vcUgnOdCqzXb0CMHzwBaS6PT9VaGaUkSzfXsdlSXzi7k49tx1NWGp7JTOrxXZhhn-Adjt",
    investmentScore: 82,
    predictedPrice: "Rs 8.1 Crore",
    predictedChangePct: 8.0,
    ownership: "Freehold",
    possession: "Ready",
    yearBuilt: 2021,
  },
  {
    id: "p8",
    title: "12 Marla House, Lake City",
    price: "Rs 3.2 Crore",
    pricePerUnit: "Rs 27 Lakh",
    location: "Lake City, Lahore",
    area: "12 Marla",
    beds: 4,
    baths: 4,
    type: "House",
    verified: true,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBsd5Bh0rOqaKMstPnO_isJ3Z0qg0G-ofXwpCZSHXQ1kQm9_8TrudEBSQQYC19638Txw0UFAcFAN4D-BK-Vjfn0nuxRzh__h2fUXFtIrYvwM0o90Fx7g2QJhfQrf6pICRPP1cspvEB72pAswNx2RrUDGC1QBFsHwo-eAuacCYhBS0WhX84Yt_Ye3rnq8cfitQqsVZZLRk4fGZR63xmnhedxVQq5EeX5OARJs59NnmRyn9CRQKU2vJzZ",
    investmentScore: 66,
    predictedPrice: "Rs 3.4 Crore",
    predictedChangePct: 6.3,
    ownership: "Freehold",
    possession: "Ready",
    yearBuilt: 2020,
  },
];

export const favouritePropertyIds = ["p1", "p2", "p3", "p4", "p5", "p6", "p7", "p8"];

export const trendingSocieties: Society[] = [
  {
    id: "s1",
    name: "Bahria Town",
    location: "Phase 8, Rawalpindi",
    tagline: "Phase 8 - 1,200 plots",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB4g-YR0e9qFRP0TGQulf_6AjOoSZZVF3SGYAFtEUMn85bLTcDAsjZ0Gmpm-MerUHBOCfXT5eZpxhg3ZE1gLH6xCLu1ifzsxwsggyY_rHC2Wknspp7WNZnSxYaBmZPYWqpTltZpH4B2aJSYvJF7DLxT_TzA1-osmiIBZzkZQ75M8b7MluhkOOpC6S1R4H02-imuMWGdCNP5SKMj-qSyoWeFQC0gC3GD5MjRsZjHuPDgm1R7MP_WjaQN",
    governmentApproved: true,
    totalPlots: 1200,
    available: 340,
    occupancyPct: 89,
    amenitiesCount: 12,
    facilities: [
      { icon: "school", label: "School" },
      { icon: "medical_services", label: "Hospital" },
      { icon: "park", label: "Park" },
      { icon: "mosque", label: "Mosque" },
      { icon: "shopping_basket", label: "Market" },
      { icon: "security", label: "Security" },
      { icon: "water_drop", label: "Water supply" },
      { icon: "gas_meter", label: "Sui gas" },
    ],
    nearbyLandmarks: [
      { icon: "local_hospital", label: "City Hospital", distanceKm: 1.2 },
      { icon: "flight", label: "International Airport", distanceKm: 8.4 },
      { icon: "school", label: "Roots International", distanceKm: 0.8 },
      { icon: "shopping_bag", label: "Giga Mall", distanceKm: 2.5 },
      { icon: "sports_cricket", label: "Sports Complex", distanceKm: 3.1 },
    ],
    timeline: [
      { year: 2020, label: "Main Gate & Road Network", status: "done" },
      { year: 2021, label: "Phase A Possession", status: "done" },
      { year: 2023, label: "Commercial Zone Completed", status: "current" },
      { year: 2025, label: "Public Hospital Opening", status: "upcoming" },
    ],
  },
  {
    id: "s2",
    name: "DHA Lahore",
    location: "Phase 6 & 7, Lahore",
    tagline: "Phase 6 & 7 - High Demand",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDqt-R9p-77tlb2880zPH4-1OiIPG3tOpBtDGE2Eah-psippm4GsNlNPw_q9CUQHoCJCIdeCNIC6Yy0t5Iykfqf_VwjzhaVyLM2kePS5h5yV73FaUVwQsvsvBYtrn0ZzlurLjoRkVbDwzw7bFMaoBS7vPjxHWWSpKqSBkViqEGHAA3D4Y7X9p05iSU65YhedzaptiLkUbqOD_8FBefMl30Ge_4ylqDuJCEKsE8z7sG6XT9KpVzW0J-P",
    governmentApproved: true,
    totalPlots: 980,
    available: 120,
    occupancyPct: 94,
    amenitiesCount: 14,
    facilities: [
      { icon: "school", label: "School" },
      { icon: "medical_services", label: "Hospital" },
      { icon: "park", label: "Park" },
      { icon: "mosque", label: "Mosque" },
      { icon: "shopping_basket", label: "Market" },
      { icon: "security", label: "Security" },
      { icon: "water_drop", label: "Water supply" },
      { icon: "gas_meter", label: "Sui gas" },
    ],
    nearbyLandmarks: [
      { icon: "local_hospital", label: "Doctors Hospital", distanceKm: 2.0 },
      { icon: "flight", label: "Allama Iqbal Airport", distanceKm: 6.1 },
      { icon: "school", label: "Beaconhouse School", distanceKm: 1.1 },
      { icon: "shopping_bag", label: "Packages Mall", distanceKm: 3.4 },
    ],
    timeline: [
      { year: 2018, label: "Boulevard Development", status: "done" },
      { year: 2020, label: "Phase 6 Possession", status: "done" },
      { year: 2023, label: "Commercial Broadway", status: "current" },
      { year: 2026, label: "Phase 7 Handover", status: "upcoming" },
    ],
  },
  {
    id: "s3",
    name: "Gulberg Greens",
    location: "Islamabad",
    tagline: "Farmhouses & Residential",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuA0Uen2du8-Ld_9BB08XBcTKxuP3QMpg--s9U9m5znPYnub7npSRKI95xKp8tYd6nKaZM2UaAS-I-K7H0k_wNSqXG0ot1Wd2-3JJAYce6v3Z7x01YZ7rC6sr4YeZwj3b1TNRvKhQtZHQaWa4xYIDVBJjbkj1k4hMRK4kvjBnMe0vPO9JHc-Xzf-Uzh7NjE2vIrh71Z8CbsOua5F_rD3GH18P_6QNTuk7UUacj95Un_Rjz19745AeIZq",
    governmentApproved: true,
    totalPlots: 640,
    available: 210,
    occupancyPct: 67,
    amenitiesCount: 9,
    facilities: [
      { icon: "school", label: "School" },
      { icon: "park", label: "Park" },
      { icon: "mosque", label: "Mosque" },
      { icon: "security", label: "Security" },
    ],
    nearbyLandmarks: [
      { icon: "local_hospital", label: "Margalla Hospital", distanceKm: 4.2 },
      { icon: "school", label: "Froebel's International", distanceKm: 2.3 },
    ],
    timeline: [
      { year: 2019, label: "Main Boulevard", status: "done" },
      { year: 2022, label: "Farmhouse Possession", status: "current" },
      { year: 2027, label: "Golf Course Extension", status: "upcoming" },
    ],
  },
  {
    id: "s4",
    name: "DHA City",
    location: "Sector 1, Karachi",
    tagline: "Sector 1 - Developing Fast",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBrUAOP7gPX8r4VTwZGBTj8RQFr_5N78La8hr50-nIlaE_ZE7ni6slpLu4bFriOStPjGTjO1Vthdh1X3g-1ncvHXA5mDRI4hhlX1w2iYOAX6-N4Euowk4Fhz-d3UaxCe3cShEw2O7gaIRXV98mZXd8IhOIP2teFT9pcCu3hcOsfPEZAh6dNuaNyzuZh3PMXGPbZzkVeWCUpm6b70E2gZnHDZHdpjDXXp8gmRV9six4gd1AiBkxiyox4",
    governmentApproved: true,
    totalPlots: 1500,
    available: 800,
    occupancyPct: 47,
    amenitiesCount: 6,
    facilities: [
      { icon: "security", label: "Security" },
      { icon: "water_drop", label: "Water supply" },
      { icon: "gas_meter", label: "Sui gas" },
    ],
    nearbyLandmarks: [
      { icon: "flight", label: "Jinnah International", distanceKm: 12.6 },
    ],
    timeline: [
      { year: 2021, label: "Road Network", status: "done" },
      { year: 2024, label: "Sector 1 Possession", status: "current" },
      { year: 2028, label: "Sector 2 Development", status: "upcoming" },
    ],
  },
  {
    id: "s5",
    name: "Lake City",
    location: "Lahore",
    tagline: "Golf View Plots",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB7E_aGmj5kpJ_4EalMaVLXfram-38VUW2Yo0DKh--wxEs4N-R4DHchBIV3vO4vitF-GjtKUtoHfxDTN8WiqYzAQKfVE1coQw1w6DWJG6yV_EjiZwQVsSZyJzjQau7wEl7sI1G_hVg5iVEfVIRBcFo63F9k0Y7dkuiwvk4faDXYN1CL-gMeGZEDD1ln5odVi8gs-sqogwYXT8N1-s6uV-L4I_Kox14J1Wwwz0DGNvrbA1y0dU-j1pFB",
    governmentApproved: true,
    totalPlots: 900,
    available: 260,
    occupancyPct: 71,
    amenitiesCount: 11,
    facilities: [
      { icon: "school", label: "School" },
      { icon: "park", label: "Park" },
      { icon: "security", label: "Security" },
      { icon: "shopping_basket", label: "Market" },
    ],
    nearbyLandmarks: [
      { icon: "school", label: "Lahore Grammar School", distanceKm: 1.5 },
      { icon: "shopping_bag", label: "Lake City Mall", distanceKm: 0.6 },
    ],
    timeline: [
      { year: 2017, label: "Golf Course Opening", status: "done" },
      { year: 2022, label: "Villa Handover", status: "current" },
      { year: 2026, label: "Marina District", status: "upcoming" },
    ],
  },
];

export const similarListings = properties.slice(1, 5);

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    icon: "sell",
    title: "Price dropped on a saved property",
    description: "DHA Phase 6 plot now listed at Rs 2.2 Crore",
    timeAgo: "2h ago",
    read: false,
    group: "Today",
  },
  {
    id: "n2",
    icon: "chat_bubble",
    title: "Seller replied to your inquiry",
    description: "Re: 10 Marla House in Gulberg III",
    timeAgo: "5h ago",
    read: false,
    group: "Today",
  },
  {
    id: "n3",
    icon: "check_circle",
    title: "Verification complete",
    description: "Your property documents have been verified by our team",
    timeAgo: "8h ago",
    read: true,
    group: "Today",
  },
  {
    id: "n4",
    icon: "search",
    title: "Saved search update",
    description: "4 new matches found for 'DHA Phase 6'",
    timeAgo: "1d ago",
    read: true,
    group: "Yesterday",
  },
  {
    id: "n5",
    icon: "home",
    title: "Welcome to Rihaish",
    description: "Start exploring verified properties in Pakistan",
    timeAgo: "1d ago",
    read: true,
    group: "Yesterday",
  },
];

export const currentUser: BuyerUser = {
  name: "Hassan Iqbal",
  role: "Buyer",
  avatarUrl:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuCgHXrHEmJufCxitWGxp_1-VND1z5w9s8A2t2w7fjMBNRWC1YKb-L3MzxP_wQ04kLrHF-5tj1aA794eniy7D2KLNmIH7TFgHIC2_Q05qypunymWizydeBnS-2AhtIsUz4ZkEdvwP1idiWltwhySeJByEO2TzOvlSLe3rVK7q5t1XBLGZKKFe_zzN9F_MEuzhY0Q9d610l7LGGISgErFUpyCSni0DKTUyKmoV4AwF2E3NJBv7uBcHU38",
  phone: "300 123 4567",
  email: "h.iqbal@gmail.com",
};

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id);
}

export function getSocietyById(id: string): Society | undefined {
  return trendingSocieties.find((s) => s.id === id);
}
